version: "3.0"
services:
  tedge:
   build: .
   hostname: tedge
   container_name: thin-edge-setup.io
   expose:
      - "1883"
      - "9080"
   ports:
      - "1883:1883"
      - "9080:9080"
   volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
   #   - ../:/app/
