version: "3.0"
services:
  tedge:
    build: ./tedge
    hostname: tedge
    container_name: thin-edge-setup.io
    expose:
      - "1883"
      - "9080"
    ports:
      - "1883:1883"
      - "9080:9080"
    environment:
      - MONGO_HOST=mongodb1
      - MONGO_PORT=27017
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  # Test version: map local directory and build angular locally (three thre changes are required in total)  
  # 1. map locally
  # 2. run in tedge cmd: npm run build to build outside of the container, the result is then mapped with the following volume mapping:  ./:/app/
  # 3. enable entrypoint ENTRYPOINT ["/bin/bash", "/app/tedge/start.sh"] in tedge/Dockerfile
  #  - ./:/app/
    - ./tedge/etc/tedge:/etc/tedge
  mqtt_collector:
    build: ./MQTT_Collector
    hostname: mqtt_collector
    container_name: mqtt_collector
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MQTT_BROKER=tedge
      - MQTT_PORT=1883
      - MONGO_HOST=mongodb1
      - MONGO_PORT=27017
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_REPLICA_SET_NAME: rsmongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command:
      [
        "--bind_ip_all",
        "--replSet",
        "rsmongo",
        "--journal",
        "--dbpath",
        "/data/db"
      ]
    volumes:
      - ./mongo/data1/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./mongo/data1/configdb:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
  mongosetup:
    image: "mongo-setup"
    build: "./mongo"
    container_name: "mongosetup"
    environment:
      TTL_DOCUMENT: 300 # documents are automatically deleted after 180 seconds
    #  MONGO_USERNAME: root
    #  MONGO_PASSWORD: example
    depends_on:
      - mongodb1
    volumes:
      - ./mongo/data2:/data/