version: "3.0"
services:
  tedge:
   build: ./
   hostname: tedge
   container_name: thin-edge-setup.io
   expose:
      - "1883"
      - "9080"
   ports:
      - "1883:1883"
      - "9080:9080"
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app/
#      - ./tedge/etc/tedge:/etc/tedge

  # tedge:
  #  image: eclipse-mosquitto
  #  hostname: tedge
  #  container_name: eclipse-mosquitto
  #  expose:
  #     - "1883"
  #     - "9001"
  #  ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #  volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
 #     - ./mosquitto/log/:/mosquitto/mosquitto.log
 
  mqtt_collector:
    build: ./MQTT_Collector
    hostname: mqtt_collector
    container_name: mqtt_collector
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MQTT_BROKER=tedge
      - MQTT_PORT=1883
      - MONGO_HOST=mongodb1
      - MONGO_PORT=27017
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
    ports:
      - "27017:27017"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmongo", "--journal", "--dbpath", "/data/db" ]
    # entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./mongo/data1/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./mongo/data1/configdb:/data/configdb
    deploy:
      restart_policy:
        condition: on-failure
  mongosetup:
      image: "mongo-setup"
      build: "./mongo"
      container_name: "mongosetup"
      depends_on:
          - mongodb1
      volumes:
          - ./mongo/data2:/data/