FROM rust:alpine as builder

ARG VERSION=0.6.1

RUN apk add --no-cache musl-dev make git

WORKDIR /app
RUN git clone -b $VERSION https://github.com/thin-edge/thin-edge.io.git

WORKDIR /app/thin-edge.io
RUN cargo build --release

FROM scratch AS export-stage
COPY --from=builder /app/thin-edge.io/target/release/tedge* .